# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/timooeltze/CLionProjects/EES

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/timooeltze/CLionProjects/EES

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/timooeltze/CLionProjects/EES/CMakeFiles /Users/timooeltze/CLionProjects/EES//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/timooeltze/CLionProjects/EES/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named colorDetection-Test

# Build rule for target.
colorDetection-Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 colorDetection-Test
.PHONY : colorDetection-Test

# fast build rule for target.
colorDetection-Test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorDetection-Test.dir/build.make CMakeFiles/colorDetection-Test.dir/build
.PHONY : colorDetection-Test/fast

#=============================================================================
# Target rules for targets named EES

# Build rule for target.
EES: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EES
.PHONY : EES

# fast build rule for target.
EES/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EES.dir/build.make CMakeFiles/EES.dir/build
.PHONY : EES/fast

colorDetection/colordetection.o: colorDetection/colordetection.cpp.o
.PHONY : colorDetection/colordetection.o

# target to build an object file
colorDetection/colordetection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EES.dir/build.make CMakeFiles/EES.dir/colorDetection/colordetection.cpp.o
.PHONY : colorDetection/colordetection.cpp.o

colorDetection/colordetection.i: colorDetection/colordetection.cpp.i
.PHONY : colorDetection/colordetection.i

# target to preprocess a source file
colorDetection/colordetection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EES.dir/build.make CMakeFiles/EES.dir/colorDetection/colordetection.cpp.i
.PHONY : colorDetection/colordetection.cpp.i

colorDetection/colordetection.s: colorDetection/colordetection.cpp.s
.PHONY : colorDetection/colordetection.s

# target to generate assembly for a file
colorDetection/colordetection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EES.dir/build.make CMakeFiles/EES.dir/colorDetection/colordetection.cpp.s
.PHONY : colorDetection/colordetection.cpp.s

colorDetection/test_colordetection.o: colorDetection/test_colordetection.cpp.o
.PHONY : colorDetection/test_colordetection.o

# target to build an object file
colorDetection/test_colordetection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorDetection-Test.dir/build.make CMakeFiles/colorDetection-Test.dir/colorDetection/test_colordetection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EES.dir/build.make CMakeFiles/EES.dir/colorDetection/test_colordetection.cpp.o
.PHONY : colorDetection/test_colordetection.cpp.o

colorDetection/test_colordetection.i: colorDetection/test_colordetection.cpp.i
.PHONY : colorDetection/test_colordetection.i

# target to preprocess a source file
colorDetection/test_colordetection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorDetection-Test.dir/build.make CMakeFiles/colorDetection-Test.dir/colorDetection/test_colordetection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EES.dir/build.make CMakeFiles/EES.dir/colorDetection/test_colordetection.cpp.i
.PHONY : colorDetection/test_colordetection.cpp.i

colorDetection/test_colordetection.s: colorDetection/test_colordetection.cpp.s
.PHONY : colorDetection/test_colordetection.s

# target to generate assembly for a file
colorDetection/test_colordetection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorDetection-Test.dir/build.make CMakeFiles/colorDetection-Test.dir/colorDetection/test_colordetection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EES.dir/build.make CMakeFiles/EES.dir/colorDetection/test_colordetection.cpp.s
.PHONY : colorDetection/test_colordetection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... EES"
	@echo "... colorDetection-Test"
	@echo "... colorDetection/colordetection.o"
	@echo "... colorDetection/colordetection.i"
	@echo "... colorDetection/colordetection.s"
	@echo "... colorDetection/test_colordetection.o"
	@echo "... colorDetection/test_colordetection.i"
	@echo "... colorDetection/test_colordetection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

