# Target specific macros
nxtOSEK = /usr/local/mindstorms/nxtOSEK
TARGET = motorDemo
TARGET_SOURCES = \
	motor.c
TOPPERS_OSEK_OIL_SOURCE = ./motor.oil
ROOT=$(nxtOSEK)

# Don't modify below part
O_PATH ?= build
include $(nxtOSEK)/ecrobot/ecrobot.mak
