# Target specific macros
nxtOSEK = /usr/local/mindstorms/nxtOSEK
TARGET = bluetooth
TARGET_SOURCES = \
	bluetooth.c
TOPPERS_OSEK_OIL_SOURCE = ./bluetooth.oil
ROOT=$(nxtOSEK)

# Don't modify below part
O_PATH ?= build
include $(nxtOSEK)/ecrobot/ecrobot.mak
