# Target specific macros
nxtOSEK = /usr/local/mindstorms/nxtOSEK
TARGET = helloworld_OSEK
TARGET_SOURCES = \
	helloworld.c
TOPPERS_OSEK_OIL_SOURCE = ./helloworld.oil
ROOT=$(nxtOSEK)

# Don't modify below part
O_PATH ?= build
include $(nxtOSEK)/ecrobot/ecrobot.mak
